# Generated by Django 5.1.2 on 2024-10-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField(default=18)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=8)),
                ('course', models.CharField(choices=[('Python', 'Python'), ('AI', 'AI'), ('Jave', 'Jave')], max_length=20)),
            ],
        ),
    ]
